"""Streamlit page: analytics -- browse saved benchmark reports and sample outputs."""

from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "src"))

from object_tracking_app.config.settings import get_settings  # noqa: E402
from object_tracking_app.utils.io import load_json  # noqa: E402

settings = get_settings()
deploy_cfg = settings.deploy.streamlit

st.set_page_config(page_title="Analytics", layout=deploy_cfg.layout)
st.title("📊 Analytics")

st.markdown(
    "This page reads whatever benchmark/evaluation reports have been generated by "
    "`scripts/evaluate.py` and lists saved outputs from previous inference runs."
)

metrics_dir = settings.resolve(settings.project_info.paths.metrics_dir)
sample_outputs_dir = settings.resolve(deploy_cfg.save_outputs_dir)

st.subheader("📈 Evaluation reports")
report_files = sorted(metrics_dir.glob("*.json")) if metrics_dir.exists() else []

if not report_files:
    st.info(
        "No evaluation reports found yet. Run:\n\n"
        "```bash\nuv run python scripts/evaluate.py\n```"
    )
else:
    chosen = st.selectbox("Select a report", options=[p.name for p in report_files])
    report_path = metrics_dir / chosen
    report = load_json(report_path)

    if report.get("num_images", 0) == 0:
        st.warning(report.get("note", "This report has no evaluated images."))
    else:
        c1, c2, c3, c4 = st.columns(4)
        c1.metric("mAP@0.5", f"{report.get('map50', 0):.3f}")
        c2.metric("Precision", f"{report.get('precision', 0):.3f}")
        c3.metric("Recall", f"{report.get('recall', 0):.3f}")
        c4.metric("FPS", f"{report.get('fps', 0):.1f}")

        st.subheader("Per-class AP")
        per_class = report.get("per_class_ap", {})
        if per_class:
            import pandas as pd

            df = pd.DataFrame(sorted(per_class.items(), key=lambda kv: kv[1], reverse=True), columns=["class", "AP"])
            st.bar_chart(df.set_index("class"))

        with st.expander("Raw report JSON"):
            st.json(report)

st.subheader("🖼️ Saved sample outputs")
if sample_outputs_dir.exists():
    outputs = sorted(sample_outputs_dir.glob("*"))
    outputs = [p for p in outputs if p.suffix.lower() in {".jpg", ".jpeg", ".png", ".mp4"}]
    if not outputs:
        st.info("No saved outputs yet. Run inference on the Image or Video pages and save results.")
    else:
        for p in outputs[-10:][::-1]:
            st.markdown(f"**{p.name}**")
            if p.suffix.lower() == ".mp4":
                st.video(str(p))
            else:
                st.image(str(p), use_container_width=True)
else:
    st.info("No sample outputs directory found yet.")
